<#
.SYNOPSIS
    Interactively collect secrets and generate backend/.env and root-level .env
    directly on the remote server via plink heredoc.

.DESCRIPTION
    Called from deploy.ps1 when secrets must be (re)written.
    Nothing is persisted to the local filesystem — secrets are streamed straight
    to the remote shell over SSH.
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)] [string] $ServerHost,
    [Parameter(Mandatory = $true)] [string] $Username,
    [Parameter(Mandatory = $true)] [string] $Password,
    [Parameter(Mandatory = $false)][int]    $Port      = 22,
    [Parameter(Mandatory = $true)] [string] $TargetDir,
    [Parameter(Mandatory = $false)][switch] $WriteBackend,
    [Parameter(Mandatory = $false)][switch] $WriteRoot
)

$ErrorActionPreference = 'Stop'

function Read-Secret {
    param(
        [string]$Prompt,
        [string]$Default = '',
        [switch]$Mask
    )
    if ($Default) {
        $full = "$Prompt [default: $Default]"
    } else {
        $full = $Prompt
    }
    if ($Mask) {
        $secure = Read-Host -Prompt $full -AsSecureString
        $bstr   = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
        $plain  = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr)
        [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr) | Out-Null
    } else {
        $plain = Read-Host -Prompt $full
    }
    if ([string]::IsNullOrWhiteSpace($plain)) { return $Default }
    return $plain
}

function New-RandomSecret {
    param([int]$Bytes = 48)
    $buf = New-Object byte[] $Bytes
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($buf)
    return (-join ($buf | ForEach-Object { $_.ToString('x2') }))
}

function Send-RemoteFile {
    <#
    Writes $Content to $RemotePath on the server using a base64 round-trip.
    Using base64 avoids any quoting / newline / special-char issues in heredocs.
    #>
    param(
        [Parameter(Mandatory=$true)][string]$RemotePath,
        [Parameter(Mandatory=$true)][string]$Content
    )
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($Content)
    $b64   = [Convert]::ToBase64String($bytes)

    # Write in chunks if extremely large; our .env files are small so a single line is fine.
    $remoteCmd = "mkdir -p `"`$(dirname '$RemotePath')`" && echo '$b64' | base64 -d > '$RemotePath' && chmod 600 '$RemotePath' && echo WROTE:'$RemotePath'"

    $plinkArgs = @('-ssh','-batch','-pw', $Password, '-P', $Port, "$Username@$ServerHost", $remoteCmd)
    $out = & plink.exe @plinkArgs 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Host ($out | Out-String) -ForegroundColor DarkYellow
        throw "Failed to write $RemotePath"
    }
}

# ---------------------------------------------------------------------------

Write-Host ""
Write-Host "--- Secret collection ---" -ForegroundColor Cyan
Write-Host "Press ENTER to accept the default shown in brackets." -ForegroundColor Gray

# Always-needed (both files use these)
$SecretKey       = Read-Secret -Prompt 'SECRET_KEY (blank = auto-generate)' -Default ''
if ([string]::IsNullOrWhiteSpace($SecretKey)) {
    $SecretKey = New-RandomSecret -Bytes 48
    Write-Host "    -> generated 96-char random SECRET_KEY" -ForegroundColor Gray
}

$UnifiedPassword = Read-Secret -Prompt 'UNIFIED_PASSWORD (platform login password)' -Default 'admin123'

$DbPassword      = Read-Secret -Prompt 'DB_PASSWORD (blank = auto-generate)' -Default '' -Mask
if ([string]::IsNullOrWhiteSpace($DbPassword)) {
    $DbPassword = (New-RandomSecret -Bytes 12)
    Write-Host "    -> generated 24-char random DB_PASSWORD" -ForegroundColor Gray
}

$DashscopeKey = ''
$DashscopeUrl = 'https://dashscope.aliyuncs.com/compatible-mode/v1'
$DashscopeModel = 'qwen3.5-plus'
$DifyKey = ''
$DifyUrl = ''
$DifyDs  = ''
$InnomateUrl = 'http://172.24.0.4/murata-flowable-process/findData'

if ($WriteBackend) {
    Write-Host ""
    Write-Host "Backend-specific secrets:" -ForegroundColor Cyan

    $DashscopeKey   = Read-Secret -Prompt 'DASHSCOPE_API_KEY' -Default ''
    $DashscopeUrl   = Read-Secret -Prompt 'DASHSCOPE_BASE_URL' -Default $DashscopeUrl
    $DashscopeModel = Read-Secret -Prompt 'DASHSCOPE_MODEL' -Default $DashscopeModel

    $DifyKey = Read-Secret -Prompt 'DIFY_API_KEY' -Default ''
    $DifyUrl = Read-Secret -Prompt 'DIFY_BASE_URL' -Default ''
    $DifyDs  = Read-Secret -Prompt 'DIFY_DATASET_ID' -Default ''

    $InnomateUrl = Read-Secret -Prompt 'INNOMATE_API_URL' -Default $InnomateUrl

    if ([string]::IsNullOrWhiteSpace($DashscopeKey)) {
        Write-Host "    WARN - DASHSCOPE_API_KEY is empty; backend LLM calls will fail." -ForegroundColor Yellow
    }
}

# ---------- Build backend/.env content ----------

if ($WriteBackend) {
    $backendEnv = @"
# Generated by deploy-to-server skill on $(Get-Date -Format 'u')
# ============================================================

# DashScope AI
DASHSCOPE_API_KEY=$DashscopeKey
DASHSCOPE_BASE_URL=$DashscopeUrl
DASHSCOPE_MODEL=$DashscopeModel

# Query-time KG extraction (lightweight model)
kg_query_model=$DashscopeModel

# Innomate API
INNOMATE_API_URL=$InnomateUrl

# Auth
SECRET_KEY=$SecretKey
UNIFIED_PASSWORD=$UnifiedPassword

# Dify Knowledge Base
DIFY_API_KEY=$DifyKey
DIFY_BASE_URL=$DifyUrl
DIFY_DATASET_ID=$DifyDs
DIFY_INDEX_DATASET_ID=

# Batch processing
BATCH_CONCURRENCY=3

# PostgreSQL (overridden by docker-compose for runtime)
DATABASE_URL=postgresql+psycopg2://appuser:$DbPassword@db:5432/ai_data_platform

# Data directories (inside container)
MD_RAW_DIR=/data/raw
MD_REDACTED_DIR=/data/redacted
INDEX_DIR=/data/index

# Prompts directory
PROMPTS_DIR=/app/prompts
"@

    Write-Host ""
    Write-Host "Writing $TargetDir/backend/.env ..." -ForegroundColor Cyan
    Send-RemoteFile -RemotePath "$TargetDir/backend/.env" -Content $backendEnv
    Write-Host "    OK" -ForegroundColor Green
}

# ---------- Build root .env (compose variable substitution) ----------

if ($WriteRoot) {
    $rootEnv = @"
# Generated by deploy-to-server skill on $(Get-Date -Format 'u')
# Used by docker-compose.prod.yml variable substitution.
# ============================================================

DB_PASSWORD=$DbPassword
SECRET_KEY=$SecretKey
UNIFIED_PASSWORD=$UnifiedPassword
"@

    Write-Host ""
    Write-Host "Writing $TargetDir/.env ..." -ForegroundColor Cyan
    Send-RemoteFile -RemotePath "$TargetDir/.env" -Content $rootEnv
    Write-Host "    OK" -ForegroundColor Green
}

Write-Host ""
Write-Host "Secret files written successfully." -ForegroundColor Green
exit 0
